# Generated by Django 3.2.8 on 2021-10-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_flashcards_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcards',
            name='user',
        ),
    ]
